spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.194.168:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Aa65241413.
logging:
  level:
    root: info
    com.example.blog: warn
  file:
    name: log/blog-dev.log
